id = "msun-dark"
name = "msun-dark"
version = "1.0.0"
schema_version = 1
authors = ["Mike Sun <mike@msun.io>"]
description = "Minimalist dark themes"
repository = "https://github.com/mikesun/msun-dark-zed"
